### ISSUE TITLE
怎么设置超时时间呢

### ISSUE THREAD

**Issue by hundunzhidian** [eldoradoel/sm-ripext-websocket#3]
如题，看了下有超时时间判断，但是我想自己设置一个，不使用默认时间

**Comment by eldoradoel** [comment]
https://www.boost.org/doc/libs/1_78_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream_base__timeout.html
boost库api如上面连接所示，修改websocket::stream_base::timeout::suggested为你需要的超时时间

**Comment by eldoradoel** [comment]
比如
    auto timeout = websocket::stream_base::timeout::suggested(beast::role_type::client);
    timeout.handshake_timeout = std::chrono::seconds(30);
    timeout.idle_timeout = std::chrono::seconds(30);
    timeout.keep_alive_pings = true;

**Comment by hundunzhidian** [comment]
看来没有通过sm设置的方法了，我改改源码看看，多谢大佬！

**Comment by eldoradoel** [comment]
可以加sm的api，但是有点麻烦，你可以自己试试
